### ISSUE TITLE
Could you provide the pre-trained Chinese language model for downloading?

### ISSUE THREAD

**Issue by gongel** [lipiji/SongNet#1]
Thanks.

**Comment by lipiji** [comment]
Sure. I am refactoring the code and I will release the model later.

**Comment by qgzang** [comment]
mark

**Comment by lipiji** [comment]
@all  the pretrained Chinese LM: https://drive.google.com/file/d/1g2tGyUwPe86vPn2nub1vkQva5lwtZ6Rd/view?usp=sharing
And the finetuned model: https://drive.google.com/file/d/16A2AzuU7slf7xj2QdLcBAorUCCaCk650/view?usp=sharing
