### ISSUE TITLE
model部分使用work函数输出的词是随机中文

### ISSUE THREAD

**Issue by Imposingapple** [lipiji/SongNet#14]
您好！
       最近在研究您的代码，您在做模型测试的时候，使用的是work_incremental函数，我这边看到您的work函数，去除了incremental_state然后用了该函数，但是输出的时候输出的是随机的中文，而且标点符号也不会显示，如下面的截图，请问这是什么情况？
![微信图片_20210330214711](https://user-images.githubusercontent.com/39848377/112999519-9aee4200-91a1-11eb-90ab-ab55522858ff.png)

**Comment by lipiji** [comment]
@Imposingapple  可以说一下你如何改的code。

**Comment by Imposingapple** [comment]
因为好像按我理解incrermental方式只在解码的时候用到，所以我只在test.py的top_k_inc函数中，将work_incremental的调用改成了work的调用，然后这个函数后面注释掉了incremental_state["bidx"] = bidx这一行。请问是我这样改的有问题嘛？

**Comment by lipiji** [comment]
> 因为好像按我理解incrermental方式只在解码的时候用到，所以我只在test.py的top_k_inc函数中，将work_incremental的调用改成了work的调用，然后这个函数后面注释掉了incremental_state["bidx"] = bidx这一行。请问是我这样改的有问题嘛？

@Imposingapple  嗯，你直接用top_k()这个解码函数就行了。不用改别的。

**Comment by Imposingapple** [comment]
您好，我用了top_k()解码函数，然后对同样的测试数据，对比了结果，结果发现top_k函数的输出，会出现不少symbol token（比如<c0><c2>）。
这是incremental decoding的输出：
![1i](https://user-images.githubusercontent.com/39848377/113503367-00f11580-9564-11eb-99c1-36f92d48b40b.png)
![2i](https://user-images.githubusercontent.com/39848377/113503370-02bad900-9564-11eb-9d85-3166de3e5be0.png)

这是直接用work函数的输出：
![1o](https://user-images.githubusercontent.com/39848377/113503373-0babaa80-9564-11eb-9c49-dca3e01b6a45.png)
![2o](https://user-images.githubusercontent.com/39848377/113503374-0d756e00-9564-11eb-9ad7-2a8d0d66e06b.png)

两个用的是相同的数据点，我代码部分应该也是没有更改过的，请问您这边跑一下也是这样的结果吗？

**Comment by lipiji** [comment]
@Imposingapple  抱歉，是bug，已fix。因实验基本用_inc，所以没发现:)
