### ISSUE TITLE
c2押韵问题

### ISSUE THREAD

**Issue by ChaooMa** [lipiji/SongNet#15]
您好，论文中提到，c2 表示押韵的字词；代码中，把最后一个字（除标点外）都标记为是押韵的。请问，这是基于宋词的特点，还是有别的考量啊？
[dataset 中代码]( https://github.com/lipiji/SongNet/blob/4771cad2baec08486c291402f8e340bcb3c8278c/data.py#L119)

**Comment by lipiji** [comment]
@ChaooMa  你好，唐诗宋词歌词等韵脚往往最后一个字，非标点，所以这里简单如此表示了。

**Comment by ChaooMa** [comment]
> @ChaooMa 你好，唐诗宋词歌词等韵脚往往最后一个字，非标点，所以这里简单如此表示了。

恩恩，明白了，谢谢
