### ISSUE TITLE
求问在Sonnet这个小数据集上的fine-tuning细节

### ISSUE THREAD

**Issue by yaolinli** [lipiji/SongNet#18]
论文里还提到一个Sonnet数据集，只有100多条数据，像这么小的数据集，可以问下微调的细节吗？比如微调了模型的几层、学习率这些？谢谢！

**Comment by lipiji** [comment]
@yaolinli   这个数据集太小，论文结果也能看出来效果很差。微调我也没有做啥特别的设置，其实可以研究一下。
