### ISSUE TITLE
Could you please explain more about Integrity evaluation?

### ISSUE THREAD

**Issue by DuYooho** [lipiji/SongNet#19]
I cannot find the codes about evaluating Integrity. Could you please release them as well as the pretrained GPT2 model mentioned in your paper? Thanks.

**Comment by lipiji** [comment]
@DuYooho  You may regard Integrity as the ppl of punctuation symbols. So after obtaining the generated results I used a LM to calculate the score. https://github.com/lipiji/Guyu
