### ISSUE TITLE
有好心人放个百度盘么

### ISSUE THREAD

**Issue by iikuku** [lipiji/SongNet#27]
谷歌盘因为某些已知原因，梯子太细，下载太困难了。
Model有木有百度盘下载地址？

**Comment by iikuku** [comment]
链接：https://pan.baidu.com/s/1D49yNj-rzWhynK8mXoeVCA 
提取码：5c0c 

我自己做好心人

**Comment by lipiji** [comment]
@iikuku  辛苦辛苦
