### ISSUE TITLE
关于预训练的疑问

### ISSUE THREAD

**Issue by 980202006** [lipiji/SongNet#3]
论文中提到，预训练按照bert来的。主要说到了完形填空任务，请问是否用到了下句预测

**Comment by lipiji** [comment]
@980202006  没有下句预测，也不完全像bert，是在auto-regressive的基础上同时预测mask

**Comment by 980202006** [comment]
好的，谢谢，请问何时能放出重构代码或者预训练模型

**Comment by lipiji** [comment]
@980202006  太忙耽误了，很快就放出来。
