### ISSUE TITLE
How to generate text containing fixed text information?

### ISSUE THREAD

**Issue by cdxeve** [lipiji/SongNet#8]
Hello, as shown in the Table 6 of the paper, you mention that "our model has the ability of refining and polishing given the format C which contains some fixed text information". So could you please tell me how to make it specifically? 😊  You could reply in Chinese if you would like to, thanks a lot!

**Comment by lipiji** [comment]
I add an example for POLISH operation, please goto: https://github.com/lipiji/SongNet/blob/master/polish.sh
